package jp.ac.asojuku.asobbs.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import lombok.Data;

/**
 * 自動ログインテーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity 
@Table(name="autologin_tbl")
@Data
public class AutologinTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 自動ログインID. */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer autologinId;

	/** ユーザーテーブル. */
	private Integer userId;	//挿入・更新用
	@OneToOne
    @JoinColumn(name="userId",insertable=false ,updatable=false)
	private UserTblEntity userTbl;

	/** トークン. */
	private String token;

	/** 有効期限. */
	private Date lmitDate;

	/**
	 * コンストラクタ.
	 */
	public AutologinTblEntity() {
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((autologinId == null) ? 0 : autologinId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		AutologinTblEntity other = (AutologinTblEntity) obj;
		if (autologinId == null) {
			if (other.autologinId != null) {
				return false;
			}
		} else if (!autologinId.equals(other.autologinId)) {
			return false;
		}
		return true;
	}

}
