package jp.ac.asojuku.asobbs.entity;

import java.io.Serializable;

import javax.persistence.Embeddable;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * 掲示板確認テーブル composite-id クラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Embeddable
public class BbsCheckTblId implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	@Embedded
	/** 掲示板テーブル. */
	private BbsTblEntity bbsTbl;

	/** ユーザーID. */
	private Integer userId;

	/**
	 * コンストラクタ.
	 */
	public BbsCheckTblId() {
	}

	/**
	 * 掲示板テーブル を設定します.
	 * 
	 * @param bbsTbl
	 *            掲示板テーブル
	 */
	public void setBbsTbl(BbsTblEntity bbsTbl) {
		this.bbsTbl = bbsTbl;
	}

	/**
	 * 掲示板テーブル を取得します.
	 * 
	 * @return 掲示板テーブル
	 */
	public BbsTblEntity getBbsTbl() {
		return this.bbsTbl;
	}

	/**
	 * ユーザーID を設定します.
	 * 
	 * @param userId
	 *            ユーザーID
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * ユーザーID を取得します.
	 * 
	 * @return ユーザーID
	 */
	public Integer getUserId() {
		return this.userId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((bbsTbl == null) ? 0 : bbsTbl.hashCode());
		result = prime * result + ((userId == null) ? 0 : userId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		BbsCheckTblId other = (BbsCheckTblId) obj;
		if (bbsTbl == null) {
			if (other.bbsTbl != null) {
				return false;
			}
		} else if (!bbsTbl.equals(other.bbsTbl)) {
			return false;
		}
		if (userId == null) {
			if (other.userId != null) {
				return false;
			}
		} else if (!userId.equals(other.userId)) {
			return false;
		}
		return true;
	}

}
