package jp.ac.asojuku.asobbs.entity;

import java.io.Serializable;

import javax.persistence.Embeddable;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * 掲示板確認テーブル composite-id クラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Embeddable
public class BbsCheckTblId implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 掲示板テーブル. */
	private Integer bbsId;

	/** ユーザーID. */
	private Integer userId;

	/**
	 * コンストラクタ.
	 */
	public BbsCheckTblId() {
	}


	/**
	 * ユーザーID を設定します.
	 * 
	 * @param userId
	 *            ユーザーID
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * ユーザーID を取得します.
	 * 
	 * @return ユーザーID
	 */
	public Integer getUserId() {
		return this.userId;
	}


	public Integer getBbsId() {
		return bbsId;
	}


	public void setBbsId(Integer bbsId) {
		this.bbsId = bbsId;
	}


}
