package jp.ac.asojuku.asobbs.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.PrePersist;
import javax.persistence.Table;

import lombok.Data;

/**
 * ブックマークテーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@Entity 
@Table(name="BOOKMARK_TBL")
public class BookmarkTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** bookmark_id. */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer bookmarkId;

	/** ユーザーテーブル. */
	@OneToOne
    @JoinColumn(name="USER_ID",insertable=true ,updatable=true)
	private UserTblEntity userTbl;

	/** 掲示板テーブル. */
	@OneToOne
    @JoinColumn(name="BBS_ID",insertable=true ,updatable=true)
	private BbsTblEntity bbsTbl;

	/** create_date_time. */
	private Date createDateTime;

	/**
	 * コンストラクタ.
	 */
	public BookmarkTblEntity() {
	}

	@PrePersist
    public void onPrePersist() {
		setCreateDateTime(new Date());
    }

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((bookmarkId == null) ? 0 : bookmarkId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		BookmarkTblEntity other = (BookmarkTblEntity) obj;
		if (bookmarkId == null) {
			if (other.bookmarkId != null) {
				return false;
			}
		} else if (!bookmarkId.equals(other.bookmarkId)) {
			return false;
		}
		return true;
	}

}
