package jp.ac.asojuku.asobbs.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * カテゴリテーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity 
@Table(name="CATEGORY_TBL")
public class CategoryTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** カテゴリID. */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer categoryId;

	/** ルームテーブル. */
	private RoomTblEntity roomTbl;

	/** カテゴリ名. */
	private String name;

	/** カテゴリにある掲示数. */
	private Integer count;

	/** 掲示板テーブル 一覧. */
	@OneToMany
	private Set<BbsTblEntity> bbsTblSet;

	/**
	 * コンストラクタ.
	 */
	public CategoryTblEntity() {
		this.bbsTblSet = new HashSet<BbsTblEntity>();
	}

	/**
	 * カテゴリID を設定します.
	 * 
	 * @param categoryId
	 *            カテゴリID
	 */
	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	/**
	 * カテゴリID を取得します.
	 * 
	 * @return カテゴリID
	 */
	public Integer getCategoryId() {
		return this.categoryId;
	}

	/**
	 * ルームテーブル を設定します.
	 * 
	 * @param roomTbl
	 *            ルームテーブル
	 */
	public void setRoomTbl(RoomTblEntity roomTbl) {
		this.roomTbl = roomTbl;
	}

	/**
	 * ルームテーブル を取得します.
	 * 
	 * @return ルームテーブル
	 */
	public RoomTblEntity getRoomTbl() {
		return this.roomTbl;
	}

	/**
	 * カテゴリ名 を設定します.
	 * 
	 * @param name
	 *            カテゴリ名
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * カテゴリ名 を取得します.
	 * 
	 * @return カテゴリ名
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * カテゴリにある掲示数 を設定します.
	 * 
	 * @param count
	 *            カテゴリにある掲示数
	 */
	public void setCount(Integer count) {
		this.count = count;
	}

	/**
	 * カテゴリにある掲示数 を取得します.
	 * 
	 * @return カテゴリにある掲示数
	 */
	public Integer getCount() {
		return this.count;
	}

	/**
	 * 掲示板テーブル 一覧を設定します.
	 * 
	 * @param bbsTblSet
	 *            掲示板テーブル 一覧
	 */
	public void setBbsTblSet(Set<BbsTblEntity> bbsTblSet) {
		this.bbsTblSet = bbsTblSet;
	}

	/**
	 * 掲示板テーブル を追加します.
	 * 
	 * @param bbsTbl
	 *            掲示板テーブル
	 */
	public void addBbsTbl(BbsTblEntity bbsTbl) {
		this.bbsTblSet.add(bbsTbl);
	}

	/**
	 * 掲示板テーブル 一覧を取得します.
	 * 
	 * @return 掲示板テーブル 一覧
	 */
	public Set<BbsTblEntity> getBbsTblSet() {
		return this.bbsTblSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((categoryId == null) ? 0 : categoryId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		CategoryTblEntity other = (CategoryTblEntity) obj;
		if (categoryId == null) {
			if (other.categoryId != null) {
				return false;
			}
		} else if (!categoryId.equals(other.categoryId)) {
			return false;
		}
		return true;
	}

}
