package jp.ac.asojuku.asobbs.entity;

import java.io.Serializable;

import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import lombok.Data;

/**
 * ルームユーザーテーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@Entity 
@Table(name="ROOM_USER_TBL")
public class RoomUserTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ルームユーザーテーブル composite-id . */
	@EmbeddedId
	private RoomUserTblId roomUserTblId;

	/** ルームテーブル. */
	@ManyToOne
    @JoinColumn(referencedColumnName="roomId",insertable=false ,updatable=false)
	private RoomTblEntity roomTbl;

	/** ユーザーテーブル. */
	@OneToOne
    @JoinColumn(name="userId",insertable=false ,updatable=false)
	private UserTblEntity userTbl;

	/** ロール. */
	private Integer roomRole;

	/**
	 * コンストラクタ.
	 */
	public RoomUserTblEntity() {
	}


	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((roomUserTblId == null) ? 0 : roomUserTblId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		RoomUserTblEntity other = (RoomUserTblEntity) obj;
		if (roomUserTblId == null) {
			if (other.roomUserTblId != null) {
				return false;
			}
		} else if (!roomUserTblId.equals(other.roomUserTblId)) {
			return false;
		}
		return true;
	}

}
