package jp.ac.asojuku.asobbs.entity;

import java.io.Serializable;

import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * ルームユーザーテーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity 
@Table(name="ROOM_USER_TBL")
public class RoomUserTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ルームユーザーテーブル composite-id . */
	@EmbeddedId
	private RoomUserTblId roomUserTblId;

	/** ルームテーブル. */
	@OneToOne
    @JoinColumn(name="roomId",insertable=false ,updatable=false)
	private RoomTblEntity roomTbl;

	/** ユーザーテーブル. */
	@OneToOne
    @JoinColumn(name="userId",insertable=false ,updatable=false)
	private UserTblEntity userTbl;

	/** ロール. */
	private Integer roomRole;

	/**
	 * コンストラクタ.
	 */
	public RoomUserTblEntity() {
	}

	/**
	 * ルームユーザーテーブル composite-id  を設定します.
	 * 
	 * @param roomUserTblId
	 *            ルームユーザーテーブル composite-id 
	 */
	public void setRoomUserTblId(RoomUserTblId roomUserTblId) {
		this.roomUserTblId = roomUserTblId;
	}

	/**
	 * ルームユーザーテーブル composite-id  を取得します.
	 * 
	 * @return ルームユーザーテーブル composite-id 
	 */
	public RoomUserTblId getRoomUserTblId() {
		return this.roomUserTblId;
	}

	/**
	 * ルームテーブル を設定します.
	 * 
	 * @param roomTbl
	 *            ルームテーブル
	 */
	public void setRoomTbl(RoomTblEntity roomTbl) {
		this.roomTbl = roomTbl;
	}

	/**
	 * ルームテーブル を取得します.
	 * 
	 * @return ルームテーブル
	 */
	public RoomTblEntity getRoomTbl() {
		return this.roomTbl;
	}

	/**
	 * ユーザーテーブル を設定します.
	 * 
	 * @param userTbl
	 *            ユーザーテーブル
	 */
	public void setUserTbl(UserTblEntity userTbl) {
		this.userTbl = userTbl;
	}

	/**
	 * ユーザーテーブル を取得します.
	 * 
	 * @return ユーザーテーブル
	 */
	public UserTblEntity getUserTbl() {
		return this.userTbl;
	}

	/**
	 * ロール を設定します.
	 * 
	 * @param roomRole
	 *            ロール
	 */
	public void setRoomRole(Integer roomRole) {
		this.roomRole = roomRole;
	}

	/**
	 * ロール を取得します.
	 * 
	 * @return ロール
	 */
	public Integer getRoomRole() {
		return this.roomRole;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((roomUserTblId == null) ? 0 : roomUserTblId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		RoomUserTblEntity other = (RoomUserTblEntity) obj;
		if (roomUserTblId == null) {
			if (other.roomUserTblId != null) {
				return false;
			}
		} else if (!roomUserTblId.equals(other.roomUserTblId)) {
			return false;
		}
		return true;
	}

}
