package jp.ac.asojuku.asobbs.entity;

import java.io.Serializable;

import javax.persistence.Embeddable;
import javax.persistence.Embedded;

/**
 * ルームユーザーテーブル composite-id クラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Embeddable
public class RoomUserTblId implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	@Embedded
	/** ルームテーブル. */
	private RoomTblEntity roomTbl;

	/** ユーザーテーブル. */
	private UserTblEntity userTbl;

	/**
	 * コンストラクタ.
	 */
	public RoomUserTblId() {
	}

	/**
	 * ルームテーブル を設定します.
	 * 
	 * @param roomTbl
	 *            ルームテーブル
	 */
	public void setRoomTbl(RoomTblEntity roomTbl) {
		this.roomTbl = roomTbl;
	}

	/**
	 * ルームテーブル を取得します.
	 * 
	 * @return ルームテーブル
	 */
	public RoomTblEntity getRoomTbl() {
		return this.roomTbl;
	}

	/**
	 * ユーザーテーブル を設定します.
	 * 
	 * @param userTbl
	 *            ユーザーテーブル
	 */
	public void setUserTbl(UserTblEntity userTbl) {
		this.userTbl = userTbl;
	}

	/**
	 * ユーザーテーブル を取得します.
	 * 
	 * @return ユーザーテーブル
	 */
	public UserTblEntity getUserTbl() {
		return this.userTbl;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((roomTbl == null) ? 0 : roomTbl.hashCode());
		result = prime * result + ((userTbl == null) ? 0 : userTbl.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		RoomUserTblId other = (RoomUserTblId) obj;
		if (roomTbl == null) {
			if (other.roomTbl != null) {
				return false;
			}
		} else if (!roomTbl.equals(other.roomTbl)) {
			return false;
		}
		if (userTbl == null) {
			if (other.userTbl != null) {
				return false;
			}
		} else if (!userTbl.equals(other.userTbl)) {
			return false;
		}
		return true;
	}

}
