package jp.ac.asojuku.asobbs.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * ルームテーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity 
@Table(name="ROOM_TBL")
public class RoomTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ルームID. */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer roomId;

	/** 名前. */
	private String name;

	/** 作成日時. */
	private Date createDate;

	/** ユーザーテーブル. */
	@OneToOne
    @JoinColumn(name="userId",insertable=false ,updatable=false)
	private UserTblEntity createUserTbl;

	/** 更新日時. */
	private Date updateDate;

	/** ユーザーテーブル. */
	@OneToOne
    @JoinColumn(name="userId",insertable=false ,updatable=false)
	private UserTblEntity updateUserTbl;

	/** カテゴリテーブル 一覧. */
	@OneToMany
    @JoinColumn(name="categoryId")
	private Set<CategoryTblEntity> categoryTblSet;

	/** ルームユーザーテーブル 一覧. */
	@OneToMany
    @JoinColumn(name="userId",insertable=false ,updatable=false)
	private Set<RoomUserTblEntity> roomUserTblSet;

	/**
	 * コンストラクタ.
	 */
	public RoomTblEntity() {
		this.categoryTblSet = new HashSet<CategoryTblEntity>();
		this.roomUserTblSet = new HashSet<RoomUserTblEntity>();
	}

	/**
	 * ルームID を設定します.
	 * 
	 * @param roomId
	 *            ルームID
	 */
	public void setRoomId(Integer roomId) {
		this.roomId = roomId;
	}

	/**
	 * ルームID を取得します.
	 * 
	 * @return ルームID
	 */
	public Integer getRoomId() {
		return this.roomId;
	}

	/**
	 * 名前 を設定します.
	 * 
	 * @param name
	 *            名前
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * 名前 を取得します.
	 * 
	 * @return 名前
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * 作成日時 を設定します.
	 * 
	 * @param createDate
	 *            作成日時
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * 作成日時 を取得します.
	 * 
	 * @return 作成日時
	 */
	public Date getCreateDate() {
		return this.createDate;
	}

	/**
	 * ユーザーテーブル を設定します.
	 * 
	 * @param createUserTbl
	 *            ユーザーテーブル
	 */
	public void setCreateUserTbl(UserTblEntity createUserTbl) {
		this.createUserTbl = createUserTbl;
	}

	/**
	 * ユーザーテーブル を取得します.
	 * 
	 * @return ユーザーテーブル
	 */
	public UserTblEntity getCreateUserTbl() {
		return this.createUserTbl;
	}

	/**
	 * 更新日時 を設定します.
	 * 
	 * @param updateDate
	 *            更新日時
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * 更新日時 を取得します.
	 * 
	 * @return 更新日時
	 */
	public Date getUpdateDate() {
		return this.updateDate;
	}

	/**
	 * ユーザーテーブル を設定します.
	 * 
	 * @param updateUserTbl
	 *            ユーザーテーブル
	 */
	public void setUpdateUserTbl(UserTblEntity updateUserTbl) {
		this.updateUserTbl = updateUserTbl;
	}

	/**
	 * ユーザーテーブル を取得します.
	 * 
	 * @return ユーザーテーブル
	 */
	public UserTblEntity getUpdateUserTbl() {
		return this.updateUserTbl;
	}

	/**
	 * カテゴリテーブル 一覧を設定します.
	 * 
	 * @param categoryTblSet
	 *            カテゴリテーブル 一覧
	 */
	public void setCategoryTblSet(Set<CategoryTblEntity> categoryTblSet) {
		this.categoryTblSet = categoryTblSet;
	}

	/**
	 * カテゴリテーブル を追加します.
	 * 
	 * @param categoryTbl
	 *            カテゴリテーブル
	 */
	public void addCategoryTbl(CategoryTblEntity categoryTbl) {
		this.categoryTblSet.add(categoryTbl);
	}

	/**
	 * カテゴリテーブル 一覧を取得します.
	 * 
	 * @return カテゴリテーブル 一覧
	 */
	public Set<CategoryTblEntity> getCategoryTblSet() {
		return this.categoryTblSet;
	}

	/**
	 * ルームユーザーテーブル 一覧を設定します.
	 * 
	 * @param roomUserTblSet
	 *            ルームユーザーテーブル 一覧
	 */
	public void setRoomUserTblSet(Set<RoomUserTblEntity> roomUserTblSet) {
		this.roomUserTblSet = roomUserTblSet;
	}

	/**
	 * ルームユーザーテーブル を追加します.
	 * 
	 * @param roomUserTbl
	 *            ルームユーザーテーブル
	 */
	public void addRoomUserTbl(RoomUserTblEntity roomUserTbl) {
		this.roomUserTblSet.add(roomUserTbl);
	}

	/**
	 * ルームユーザーテーブル 一覧を取得します.
	 * 
	 * @return ルームユーザーテーブル 一覧
	 */
	public Set<RoomUserTblEntity> getRoomUserTblSet() {
		return this.roomUserTblSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((roomId == null) ? 0 : roomId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		RoomTblEntity other = (RoomTblEntity) obj;
		if (roomId == null) {
			if (other.roomId != null) {
				return false;
			}
		} else if (!roomId.equals(other.roomId)) {
			return false;
		}
		return true;
	}

}
