INSERT INTO COURSE_MASTER(COURSE_ID,COURSE_NAME)VALUES(0,"情報システム科");
INSERT INTO COURSE_MASTER(COURSE_ID,COURSE_NAME)VALUES(1,"情報システム専攻科");
INSERT INTO COURSE_MASTER(COURSE_ID,COURSE_NAME)VALUES(2,"情報工学科");
INSERT INTO COURSE_MASTER(COURSE_ID,COURSE_NAME)VALUES(3,"組込みシステム科");
INSERT INTO COURSE_MASTER(COURSE_ID,COURSE_NAME)VALUES(4,"ネットワーク科");
INSERT INTO COURSE_MASTER(COURSE_ID,COURSE_NAME)VALUES(999,"その他");

INSERT INTO ROLE_MASTER(ROLE_ID,ROLE_NAME)VALUES(0,"学生");
INSERT INTO ROLE_MASTER(ROLE_ID,ROLE_NAME)VALUES(1,"教員");
INSERT INTO ROLE_MASTER(ROLE_ID,ROLE_NAME)VALUES(2,"管理者");

INSERT INTO USER_TBL(USER_ID,MAILADRESS,PASSWORD,STUDENT_NO,NAME,NICK_NAME,ACCOUNT_EXPRY_DATE,PASSWORD_EXPIRYDATE,COURSE_ID,ROLE_ID,IS_FIRST_FLG,CERTIFY_ERR_CNT,IS_LOCK_FLG,ENTRY_DATE,UPDATE_DATE)
VALUES(NULL,"nishino@asojuku.ac.jp","a2b06f65cf9c6797c6d3e8ae38d618b0","0000001","123456789","西野先生",null,null,1,2,1,0,0,CURRENT_DATE,CURRENT_DATE);
